version: '2.1'

services:

  messages:
    container_name: messages
    build: ./
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    links:
      - redis

  redis:
    image: sameersbn/redis:4.0.9-1
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: always
